version: '3.9'
services:
  scrum-api-app:
    # command: ["sh", "-c", "python ./manage.py migrate && python debugpy --wait-for-client --listen 0.0.0.0:5678 ./manage.py runserver 0.0.0.0:8000"]
    command: > #command that is used to run the service
          sh -c "python manage.py migrate && \
                  python -m debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
      - 5678:5678