"""
This type stub file was generated by pyright.
"""

from django.db.models import CharField

VALIDATORS_PER_FORMAT = ...
DEFAULT_PER_FORMAT = ...
class ColorField(CharField):
    default_validators = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def formfield(self, **kwargs): # -> Field | None:
        ...
    
    def contribute_to_class(self, cls, name, **kwargs): # -> None:
        ...
    
    def deconstruct(self): # -> tuple[str, str, Sequence[Any], dict[str, Any]]:
        ...
    
    def validate(self, value, *args, **kwargs): # -> None:
        """
        Override validation logic to make it case-insensitive.
        """
        ...
    


