"""
This type stub file was generated by pyright.
"""

from django.contrib import admin
from django.contrib.admin.options import csrf_protect_m

class BaseOrderedModelAdmin:
    """
    Functionality common to both OrderedModelAdmin and OrderedInlineMixin.
    """
    request_query_string = ...
    @csrf_protect_m
    def changelist_view(self, request, extra_context=...):
        ...
    


class OrderedModelAdmin(BaseOrderedModelAdmin, admin.ModelAdmin):
    def get_urls(self): # -> list[URLPattern]:
        ...
    
    def move_view(self, request, object_id, direction): # -> HttpResponseRedirect:
        ...
    
    def move_up_down_links(self, obj): # -> SafeString:
        ...
    


class OrderedInlineModelAdminMixin:
    """
    ModelAdminMixin for classes that contain OrderedInilines
    """
    def get_urls(self):
        ...
    


class OrderedInlineMixin(BaseOrderedModelAdmin):
    def get_urls(self): # -> list[URLPattern]:
        ...
    
    def move_view(self, request, admin_id, object_id, direction): # -> HttpResponseRedirect:
        ...
    
    def move_up_down_links(self, obj): # -> SafeString | Literal['']:
        ...
    


class OrderedTabularInline(OrderedInlineMixin, admin.TabularInline):
    ...


class OrderedStackedInline(OrderedInlineMixin, admin.StackedInline):
    ...


