"""
This type stub file was generated by pyright.
"""

from django.db import models

def get_lookup_value(obj, field): # -> Any | None:
    ...

class OrderedModelQuerySet(models.QuerySet):
    def get_max_order(self): # -> Any | None:
        ...
    
    def get_min_order(self): # -> Any | None:
        ...
    
    def get_next_order(self): # -> Any | Literal[0]:
        ...
    
    def above(self, order, inclusive=...): # -> Self:
        """Filter items above order."""
        ...
    
    def above_instance(self, ref, inclusive=...): # -> Self:
        """Filter items above ref's order."""
        ...
    
    def below(self, order, inclusive=...): # -> Self:
        """Filter items below order."""
        ...
    
    def below_instance(self, ref, inclusive=...): # -> Self:
        """Filter items below ref's order."""
        ...
    
    def decrease_order(self, **extra_kwargs): # -> int:
        """Decrease `order_field_name` value by 1."""
        ...
    
    def increase_order(self, **extra_kwargs): # -> int:
        """Increase `order_field_name` value by 1."""
        ...
    
    def bulk_create(self, objs, *args, **kwargs): # -> list[Any]:
        ...
    


class OrderedModelManager(models.Manager.from_queryset(OrderedModelQuerySet)):
    ...


class OrderedModelBase(models.Model):
    """
    An abstract model that allows objects to be ordered relative to each other.
    Usage (See ``OrderedModel``):
     - create a model subclassing ``OrderedModelBase``
     - add an indexed ``PositiveIntegerField`` to the model
     - set ``order_field_name`` to the name of that field
     - use the same field name in ``Meta.ordering``
    [optional]
     - set ``order_with_respect_to`` to limit order to a subset
     - specify ``order_class_path`` in case of polymorphic classes
    """
    objects = ...
    order_field_name = ...
    order_with_respect_to = ...
    order_class_path = ...
    class Meta:
        abstract = ...
    
    
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    @classmethod
    def get_order_with_respect_to(cls): # -> tuple[Never] | tuple[Any, ...]:
        ...
    
    def get_ordering_queryset(self, qs=..., wrt=...): # -> QuerySet[Any, Any] | Any:
        ...
    
    def previous(self): # -> Any:
        """
        Get previous element in this object's ordered stack.
        """
        ...
    
    def next(self): # -> Any:
        """
        Get next element in this object's ordered stack.
        """
        ...
    
    def save(self, *args, **kwargs): # -> None:
        ...
    
    def delete(self, *args, extra_update=..., **kwargs): # -> None:
        ...
    
    def swap(self, replacement): # -> None:
        """
        Swap the position of this object with a replacement object.
        """
        ...
    
    def up(self): # -> None:
        """
        Move this object up one position.
        """
        ...
    
    def down(self): # -> None:
        """
        Move this object down one position.
        """
        ...
    
    def to(self, order, extra_update=...): # -> None:
        """
        Move object to a certain position, updating all affected objects to move accordingly up or down.
        """
        ...
    
    def above(self, ref, extra_update=...): # -> None:
        """
        Move this object above the referenced object.
        """
        ...
    
    def below(self, ref, extra_update=...): # -> None:
        """
        Move this object below the referenced object.
        """
        ...
    
    def top(self, extra_update=...): # -> None:
        """
        Move this object to the top of the ordered stack.
        """
        ...
    
    def bottom(self, extra_update=...): # -> None:
        """
        Move this object to the bottom of the ordered stack.
        """
        ...
    
    @classmethod
    def check(cls, **kwargs): # -> list[CheckMessage]:
        ...
    


class OrderedModel(OrderedModelBase):
    """
    An abstract model that allows objects to be ordered relative to each other.
    Provides an ``order`` field.
    """
    order = ...
    order_field_name = ...
    class Meta:
        abstract = ...
        ordering = ...
    
    


