"""
This type stub file was generated by pyright.
"""

from rest_framework import serializers

class OrderedModelSerializer(serializers.ModelSerializer):
    """
    A ModelSerializer to provide a serializer that can be update and create
    objects in a specific order.

    Typically a `models.PositiveIntegerField` field called `order` is used to
    store the order of the Model objects. This field can be customized by setting
    the `order_field_name` attribute on the Model class.

    This serializer will move the object to the correct
    order if the ordering field is passed in the validated data.
    """
    def get_order_field(self): # -> Any:
        """
        Return the field name for the ordering field.

        If inheriting from `OrderedModelBase`, the `order_field_name` attribute
        must be set on the Model class. If inheriting from `OrderedModel`, the
        `order_field_name` attribute is not required, as the `OrderedModel`
        has the `order_field_name` attribute defaulting to 'order'.

        Returns:
            str: The field name for the ordering field.

        Raises:
            AttributeError: If the `order_field_name` attribute is not set,
                either on the Model class or on the serializer's Meta class.
        """
        ...
    
    def get_fields(self): # -> dict[str, Field[Any, Any, Any, Any]]:
        ...
    
    def update(self, instance, validated_data):
        """
        Update the instance.

        If the `order_field_name` attribute is passed in the validated data,
        the instance will be moved to the specified order.

        Returns:
            Model: The updated instance.
        """
        ...
    
    def create(self, validated_data):
        """
        Create a new instance.

        If the `order_field_name` attribute is passed in the validated data,
        the instance will be created at the specified order.

        Returns:
            Model: The created instance.
        """
        ...
    


