"""
This type stub file was generated by pyright.
"""

from django.forms.fields import CharField, ChoiceField, MultiValueField
from phonenumber_field import widgets

GEO_COUNTRY_CODE_TO_REGION_CODE = ...
REGION_CODE_TO_COUNTRY_CODE = ...
class PhoneNumberField(CharField):
    default_validators = ...
    widget = widgets.RegionalPhoneNumberWidget
    def __init__(self, *args, region=..., widget=..., **kwargs) -> None:
        """
        :keyword str region: 2-letter country code as defined in ISO 3166-1.
            When not supplied, defaults to :setting:`PHONENUMBER_DEFAULT_REGION`
        :keyword django.forms.Widget widget: defaults to
            :class:`~phonenumber_field.widgets.RegionalPhoneNumberWidget`
        """
        ...
    
    def to_python(self, value): # -> str | Any | PhoneNumber | None:
        ...
    


def localized_choices(language): # -> list[tuple[str, str]]:
    ...

class PrefixChoiceField(ChoiceField):
    def __init__(self, *, choices=..., **kwargs) -> None:
        ...
    


class SplitPhoneNumberField(MultiValueField):
    default_validators = ...
    widget = widgets.PhoneNumberPrefixWidget
    def __init__(self, *, initial=..., region=..., widget=..., **kwargs) -> None:
        """
        :keyword list initial: A two-elements iterable:

            #. the region code, an :class:`str`, the 2-letter country code
               as defined in ISO 3166-1.

            #. the phone number, an :class:`str`

            When ``initial`` is not provided, the ``region`` keyword argument
            is used as the initial for the region field if specified, otherwise
            :setting:`PHONENUMBER_DEFAULT_REGION` is used.

            See :attr:`django.forms.Field.initial`.
        :keyword str region: 2-letter country code as defined in ISO 3166-1.
            When not supplied, defaults to :setting:`PHONENUMBER_DEFAULT_REGION`
        :keyword ~django.forms.MultiWidget widget: defaults to
            :class:`~phonenumber_field.widgets.PhoneNumberPrefixWidget`
        """
        ...
    
    def prefix_field(self): # -> PrefixChoiceField:
        """
        Returns the default :class:`~django.forms.Field` for the phone
        number prefix field.

        Use this hook to set widget attributes or update the field definition.
        """
        ...
    
    def number_field(self): # -> CharField:
        """
        Returns the default :class:`~django.forms.Field` for the phone
        number field.

        Use this hook to set widget attributes or update the field definition.
        """
        ...
    
    def invalid_error_message(self): # -> str:
        """
        Hook to customize ``error_messages["invalid"]`` for a given region.

        Include the example number in the message with the ``{example_number}``
        placeholder.
        """
        ...
    
    def compress(self, data_list): # -> Any | PhoneNumber:
        ...
    
    def clean(self, value): # -> Any:
        ...
    


