"""
This type stub file was generated by pyright.
"""

from typing import Optional
from django.db import models
from django.forms import Field
from phonenumber_field.phonenumber import PhoneNumber

class PhoneNumberDescriptor:
    """
    The descriptor for the phone number attribute on the model instance.
    Returns a PhoneNumber when accessed so you can do stuff like::

        >>> instance.phone_number.as_international

    Assigns a phone number object on assignment so you can do::

        >>> instance.phone_number = PhoneNumber(...)

    or,

        >>> instance.phone_number = '+414204242'
    """
    def __init__(self, field) -> None:
        ...
    
    def __get__(self, instance, owner): # -> Self | Any:
        ...
    
    def __set__(self, instance, value): # -> None:
        ...
    


class PhoneNumberField(models.CharField):
    attr_class = PhoneNumber
    descriptor_class = PhoneNumberDescriptor
    default_validators = ...
    description = ...
    def __init__(self, *args, region=..., **kwargs) -> None:
        """
        :keyword str region: 2-letter country code as defined in ISO 3166-1.
            When not supplied, defaults to :setting:`PHONENUMBER_DEFAULT_REGION`
        :keyword int max_length: The maximum length of the underlying char field.
        """
        ...
    
    @property
    def region(self): # -> Any | None:
        ...
    
    def check(self, **kwargs): # -> list[CheckMessage]:
        ...
    
    def get_prep_value(self, value): # -> Any:
        """
        Perform preliminary non-db specific value checks and conversions.
        """
        ...
    
    def from_db_value(self, value, expression, connection): # -> PhoneNumber:
        ...
    
    def contribute_to_class(self, cls, name, *args, **kwargs): # -> None:
        ...
    
    def deconstruct(self): # -> tuple[str, str, Sequence[Any], dict[str, Any]]:
        ...
    
    def formfield(self, form_class=..., choices_form_class=..., **kwargs) -> Optional[Field]:
        ...
    


