"""
This type stub file was generated by pyright.
"""

import phonenumbers
from functools import total_ordering
from typing import TYPE_CHECKING
from typing_extensions import Self

if TYPE_CHECKING:
    ...
@total_ordering
class PhoneNumber(phonenumbers.PhoneNumber):
    """
    A extended version of phonenumbers.PhoneNumber that provides
    some neat and more pythonic, easy to access methods. This makes using a
    PhoneNumber instance much easier, especially in templates and such.
    """
    format_map = ...
    @classmethod
    def from_string(cls, phone_number, region=...) -> Self:
        """
        :arg str phone_number: parse this :class:`str` as a phone number.
        :keyword str region: 2-letter country code as defined in ISO 3166-1.
            When not supplied, defaults to :setting:`PHONENUMBER_DEFAULT_REGION`
        """
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def is_valid(self): # -> bool:
        """
        Whether the number supplied is actually valid.

        :return: ``True`` when the phone number is valid.
        :rtype: bool
        """
        ...
    
    def format_as(self, format): # -> str:
        ...
    
    @property
    def as_international(self): # -> str:
        ...
    
    @property
    def as_e164(self): # -> str:
        ...
    
    @property
    def as_national(self): # -> str:
        ...
    
    @property
    def as_rfc3966(self): # -> str:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __eq__(self, other) -> bool:
        """
        Override parent equality because we store only string representation
        of phone number, so we must compare only this string representation
        """
        ...
    
    def __lt__(self, other) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    


def to_python(value, region=...): # -> PhoneNumber:
    ...

def validate_region(region): # -> None:
    ...

