"""
This type stub file was generated by pyright.
"""

from django.forms.widgets import MultiWidget, TextInput

class PhoneNumberPrefixWidget(MultiWidget):
    """
    Companion widget of :class:`~phonenumber_field.formfields.SplitPhoneNumberField`.
    """
    def decompress(self, value): # -> list[str | None] | list[None]:
        ...
    


class RegionalPhoneNumberWidget(TextInput):
    """
    A :class:`~django.forms.Widget` that prefers displaying numbers in the
    national format, and falls back to :setting:`PHONENUMBER_DEFAULT_FORMAT`
    for international numbers.
    """
    input_type = ...
    def __init__(self, region=..., attrs=...) -> None:
        """
        :keyword str region: 2-letter country code as defined in ISO 3166-1.
            When not supplied, defaults to :setting:`PHONENUMBER_DEFAULT_REGION`
        :keyword dict attrs: See :attr:`django.forms.Widget.attrs`
        """
        ...
    
    def format_value(self, value): # -> str | None:
        ...
    


