# Generated by Django 3.2.15 on 2022-09-16 23:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "sub_task",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True), size=None
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[(0, "Urgent"), (1, "Medium"), (2, "Low")],
                        default="Low",
                        max_length=6,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
