# Generated by Django 3.2.15 on 2022-09-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="link",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
