# Generated by Django 3.2.15 on 2022-09-22 14:37

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_task_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                null=True, upload_to=core.models.user_image_file_path
            ),
        ),
    ]
