# Generated by Django 3.2.16 on 2023-01-07 17:45


import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20230107_1723"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="sub_tasks",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, max_length=255),
                blank=True,
                default=[],
                size=None,
            ),
        ),
    ]
