# Generated by Django 3.2.16 on 2023-03-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_subtask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="sub_tasks",
        ),
    ]
