# Generated by Django 3.2.16 on 2023-03-20 16:50

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_task_sub_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="created_at",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
