# Generated by Django 3.2.18 on 2023-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, default=list, related_name='assignee', to='core.Contact'),
        ),
    ]
