# Generated by Django 3.2.18 on 2023-05-10 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_auto_20230426_2127"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                blank=True, related_name="assignees", to="core.Contact"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("Urgent", "Urgent"), ("Medium", "Medium"), ("Low", "Low")],
                default="Low",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="subtasks",
            field=models.ManyToManyField(
                blank=True, related_name="subtasks", to="core.Subtask"
            ),
        ),
    ]
