# Generated by Django 3.2.18 on 2023-05-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_board_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lists",
                to="core.board",
            ),
        ),
    ]
