# Generated by Django 3.2.18 on 2023-08-05 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_task_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="core.list",
            ),
        ),
    ]
