# Generated by Django 3.2.18 on 2023-11-16 07:37

from django.db import migrations, models


def assign_positions(apps, schema_editor):
    List = apps.get_model("core", "List")
    Board = apps.get_model("core", "Board")
    for board in Board.objects.all():
        # Fetch lists with position less than or equal to 0 or position is null
        lists = (
            List.objects.filter(board=board)
            .filter(models.Q(position__lte=0) | models.Q(position__isnull=True))
            .order_by("created_at")
        )
        for idx, list_obj in enumerate(lists, start=1):
            list_obj.position = idx
            list_obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_task_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="position",
            field=models.IntegerField(null=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="list",
            constraint=models.UniqueConstraint(
                fields=("board", "position"), name="unique_position_per_board"
            ),
        ),
        migrations.RunPython(assign_positions),
    ]
