# Generated by Django 3.2.18 on 2023-11-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_auto_20231116_0737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="position",
            field=models.IntegerField(),
        ),
    ]
