# Generated by Django 3.2.18 on 2023-11-17 20:01

from django.db import migrations, models


def assign_positions(apps, schema_editor):
    Task = apps.get_model("core", "Task")
    List = apps.get_model("core", "List")
    for list in List.objects.all():
        # Fetch tasks with position less than or equal to 0 or position is null
        tasks = (
            Task.objects.filter(list=list)
            .filter(models.Q(position__lte=0) | models.Q(position__isnull=True))
            .order_by("created_at")
        )
        for idx, task_obj in enumerate(tasks, start=1):
            task_obj.position = idx
            task_obj.save()

    # Then, handle tasks where list is None
    tasks_without_list = (
        Task.objects.filter(list__isnull=True)
        .filter(models.Q(position__lte=0) | models.Q(position__isnull=True))
        .order_by("created_at")
    )
    for idx, task_obj in enumerate(tasks_without_list, start=1):
        task_obj.position = idx
        task_obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_alter_list_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="position",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="list",
            name="position",
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("list", "position"), name="unique_position_per_list"
            ),
        ),
        migrations.RunPython(assign_positions),
    ]
