# Generated by Django 3.2.25 on 2024-04-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_user_is_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("user", "email"), name="unique_user_email"
            ),
        ),
    ]
