# Generated by Django 3.2.25 on 2024-04-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_auto_20240421_1703"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(default="Anonymous", max_length=255),
        ),
    ]
