# Generated by Django 3.2.25 on 2024-04-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_contact_unique_user_phone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_user_phone',
        ),
    ]
