# Generated by Django 5.2.4 on 2025-08-15 11:03

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_auto_20240429_1315"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contact",
            name="unique_user_email",
        ),
        migrations.RemoveConstraint(
            model_name="contact",
            name="unique_user_phone",
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(
                default="Untitled",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_title",
                        message="Title must contain only letters, numbers, and spaces.",
                        regex="^[a-zA-Z0-9]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFF0000", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="issue",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_name",
                        message="Name must contain only low letters.",
                        regex="^[a-z]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(default="Anonymous", max_length=50),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="list",
            name="name",
            field=models.CharField(default="untitled", max_length=25),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__exact", ""), _negated=True),
                fields=("user", "email"),
                name="unique_user_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_number__exact", ""), _negated=True),
                fields=("user", "phone_number"),
                name="unique_user_phone",
            ),
        ),
    ]
