# Generated by Django 5.2.4 on 2025-08-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_remove_contact_unique_user_email_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="List",
            new_name="ListOfTasks",
        ),
    ]
