# Generated by Django 5.2.4 on 2025-08-15 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_alter_board_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(
                default="Untitled",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_title",
                        message="Title must contain only letters, numbers, and spaces.\nInput must be between 5 and 50 characters long.",
                        regex="^(?=.5,50$)[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$",
                    )
                ],
            ),
        ),
    ]
