# Generated by Django 5.2.4 on 2025-08-16 08:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_alter_board_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(
                default="Untitled",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_title",
                        message="Title must contain only letters, numbers, and spaces. Must be between 5 and 50 characters long.",
                        regex="^(?=.5,50$)[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="listoftasks",
            name="board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="list_of_tasks",
                to="core.board",
            ),
        ),
    ]
