# Generated by Django 5.2.4 on 2025-08-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_alter_board_title_alter_listoftasks_board"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="board",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("title__regex", "^(?=.5,50$)[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$")
                ),
                name="core_board_title_alphanumeric_check",
            ),
        ),
    ]
