# Generated by Django 5.2.4 on 2025-08-16 20:19

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_board_core_board_title_alphanumeric_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(
                default="Untitled",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_invalid",
                        message="Must contain only letters, numbers, and spaces. Must be between 5 and 50 characters long.",
                        regex="^(?=.5,50$)[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="issue",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_invalid",
                        message="Must contain only lowercase letters. Must be between 5 and 50 characters long.",
                        regex="^(?=.5,50$)[a-z]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="listoftasks",
            name="name",
            field=models.CharField(
                default="untitled",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_invalid",
                        message="Must contain only letters, numbers, and spaces. Must be between 5 and 50 characters long.",
                        regex="^(?=.5,50$)[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="listoftasks",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("name__regex", "^(?=.5,50$)[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$")
                ),
                name="core_listoftasks_name_alphanumeric_check",
            ),
        ),
    ]
