# Generated by Django 5.2.4 on 2025-08-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_alter_board_title_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(blank=True, default="Anonymous", max_length=50),
        ),
    ]
