# Generated by Django 5.2.4 on 2025-08-22 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_alter_contact_email_alter_contact_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="board",
            name="core_board_title_alphanumeric_check",
        ),
        migrations.RemoveConstraint(
            model_name="contact",
            name="unique_user_email",
        ),
        migrations.RemoveConstraint(
            model_name="contact",
            name="unique_user_phone",
        ),
        migrations.RemoveConstraint(
            model_name="listoftasks",
            name="core_listoftasks_name_alphanumeric_check",
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(
                default="Untitled",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_not_alphanumeric",
                        message="Must contain only letters, numbers, and spaces.",
                        regex="^[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^(?=.5,50$).*$",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="issue",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_not_lower_case",
                        message="Must contain only lowercase letters.",
                        regex="^[a-z]+$",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^(?=.5,50$).*$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(
                blank=True,
                default="Anonymous",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^(?=.5,50$).*$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="listoftasks",
            name="name",
            field=models.CharField(
                default="untitled",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_not_alphanumeric",
                        message="Must contain only letters, numbers, and spaces.",
                        regex="^[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^(?=.5,50$).*$",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("title__regex", "^[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$")
                ),
                name="core_board_title_alphanumeric_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.CheckConstraint(
                condition=models.Q(("title__regex", "^(?=.5,50$).*$")),
                name="core_board_title_length_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.CheckConstraint(
                condition=models.Q(("title__regex", "^\\s+|\\s+$|\\s+(?=\\s)")),
                name="core_board_title_spacing_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", "^[a-z]+$")),
                name="core_category_name_lower_alphabetic_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", "^(?=.5,50$).*$")),
                name="core_category_name_length_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__exact", ""), _negated=True),
                fields=("user", "email"),
                name="core_contact_user_email_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_number__exact", ""), _negated=True),
                fields=("user", "phone_number"),
                name="core_contact_user_phone_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email", ""),
                    ("email__regex", "^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$"),
                    _connector="OR",
                ),
                name="core_contact_email_format_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("name", ""),
                    models.Q(
                        ("name__regex", "^\\s+|\\s+$|\\s+(?=\\s)"),
                        ("name__regex", "^(?=.5,50$).*$"),
                    ),
                    _connector="OR",
                ),
                name="core_contact_name_format_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="listoftasks",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", "^[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$")),
                name="core_listoftasks_name_alphanumeric_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="listoftasks",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", "^(?=.5,50$).*$")),
                name="core_listoftasks_name_length_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="listoftasks",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", "^\\s+|\\s+$|\\s+(?=\\s)")),
                name="core_listoftasks_name_spacing_check",
            ),
        ),
    ]
