# Generated by Django 5.2.4 on 2025-08-22 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_remove_board_core_board_title_alphanumeric_check_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contact",
            name="core_contact_email_format_check",
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_email_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^(?=.5,50$).*$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email", ""),
                    models.Q(
                        ("email__regex", "^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$"),
                        ("email__regex", "^(?=.5,50$).*$"),
                    ),
                    _connector="OR",
                ),
                name="core_contact_email_format_check",
            ),
        ),
    ]
