# Generated by Django 5.2.4 on 2025-08-22 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_remove_contact_core_contact_email_format_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                default="Untitled",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_not_alphanumeric",
                        message="Must contain only letters, numbers, and spaces.",
                        regex="^[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^(?=.5,50$).*$",
                    ),
                ],
            ),
        ),
        migrations.AlterConstraint(
            model_name="board",
            name="core_board_title_alphanumeric_check",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("title__regex", "^[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$")
                ),
                name="core_board_title_alphanumeric_check",
                violation_error_message="Must contain only letters, numbers, and spaces.",
            ),
        ),
    ]
