# Generated by Django 5.2.4 on 2025-08-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_remove_board_core_board_title_alphanumeric_check_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="board",
            name="core_board_title_check",
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("title__regex", "^(?=.5,50$).*$"),
                    models.Q(
                        ("title__regex", "^\\s+|\\s+$|\\s+(?=\\s)"), _negated=True
                    ),
                ),
                name="core_board_title_check",
            ),
        ),
    ]
