# Generated by Django 5.2.4 on 2025-08-27 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_remove_board_core_board_title_check_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="board",
            name="core_board_title_check",
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="core_category_name_check",
        ),
        migrations.RemoveConstraint(
            model_name="contact",
            name="core_contact_email_check",
        ),
        migrations.RemoveConstraint(
            model_name="contact",
            name="core_contact_name_check",
        ),
        migrations.RemoveConstraint(
            model_name="listoftasks",
            name="core_listoftasks_name_check",
        ),
        migrations.RemoveConstraint(
            model_name="subtask",
            name="core_subtask_title_check",
        ),
        migrations.RemoveConstraint(
            model_name="task",
            name="core_task_title_check",
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(
                default="Untitled",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^.{5,50}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="issue",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^.{5,50}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_email_invalid",
                        message="Invalid email address.",
                        regex="^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_email_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^.{5,50}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(
                blank=True,
                default="Anonymous",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^.{5,50}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="listoftasks",
            name="name",
            field=models.CharField(
                default="untitled",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^.{5,50}$",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="title",
            field=models.CharField(
                default="Untitled",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^.{5,50}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                default="Untitled",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^.{5,50}$",
                    ),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("title__regex", "^.{5,50}$"),
                    models.Q(
                        ("title__regex", "^\\s+|\\s+$|\\s+(?=\\s)"), _negated=True
                    ),
                ),
                name="core_board_title_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("name__regex", "^.{5,50}$"),
                    ("name__regex", "^\\s+|\\s+$|\\s+(?=\\s)"),
                ),
                name="core_category_name_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email", ""),
                    models.Q(
                        ("email__regex", "^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$"),
                        ("email__regex", "^.{5,50}$"),
                    ),
                    _connector="OR",
                ),
                name="core_contact_email_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("name", ""),
                    models.Q(
                        ("name__regex", "^\\s+|\\s+$|\\s+(?=\\s)"),
                        ("name__regex", "^.{5,50}$"),
                    ),
                    _connector="OR",
                ),
                name="core_contact_name_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="listoftasks",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("name__regex", "^.{5,50}$"),
                    ("name__regex", "^\\s+|\\s+$|\\s+(?=\\s)"),
                ),
                name="core_listoftasks_name_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="subtask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("title__regex", "^.{5,50}$"),
                    ("title__regex", "^\\s+|\\s+$|\\s+(?=\\s)"),
                ),
                name="core_subtask_title_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("title__regex", "^.{5,50}$"),
                    ("title__regex", "^\\s+|\\s+$|\\s+(?=\\s)"),
                ),
                name="core_task_title_check",
            ),
        ),
    ]
