# Generated by Django 5.2.4 on 2025-08-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_remove_board_core_board_title_check_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="core_category_name_check",
        ),
        migrations.RemoveConstraint(
            model_name="contact",
            name="core_contact_name_check",
        ),
        migrations.RemoveConstraint(
            model_name="listoftasks",
            name="core_listoftasks_name_check",
        ),
        migrations.RemoveConstraint(
            model_name="subtask",
            name="core_subtask_title_check",
        ),
        migrations.RemoveConstraint(
            model_name="task",
            name="core_task_title_check",
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("name__regex", "^.{5,50}$"),
                    models.Q(("name__regex", "^\\s+|\\s+$|\\s+(?=\\s)"), _negated=True),
                ),
                name="core_category_name_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("name", ""),
                    models.Q(
                        ("name__regex", "^.{5,50}$"),
                        models.Q(
                            ("name__regex", "^\\s+|\\s+$|\\s+(?=\\s)"), _negated=True
                        ),
                    ),
                    _connector="OR",
                ),
                name="core_contact_name_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="listoftasks",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("name__regex", "^.{5,50}$"),
                    models.Q(("name__regex", "^\\s+|\\s+$|\\s+(?=\\s)"), _negated=True),
                ),
                name="core_listoftasks_name_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="subtask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("title__regex", "^.{5,50}$"),
                    models.Q(
                        ("title__regex", "^\\s+|\\s+$|\\s+(?=\\s)"), _negated=True
                    ),
                ),
                name="core_subtask_title_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("title__regex", "^.{5,50}$"),
                    models.Q(
                        ("title__regex", "^\\s+|\\s+$|\\s+(?=\\s)"), _negated=True
                    ),
                ),
                name="core_task_title_check",
            ),
        ),
    ]
