# Generated by Django 5.2.4 on 2025-08-27 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_remove_category_core_category_name_check_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contact",
            name="core_contact_email_check",
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_email_invalid",
                        message="Invalid email address.",
                        regex="^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="listoftasks",
            name="name",
            field=models.CharField(
                default="Unnamed",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^.{5,50}$",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email", ""),
                    ("email__regex", "^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$"),
                    _connector="OR",
                ),
                name="core_contact_email_check",
            ),
        ),
    ]
