# Generated by Django 5.2.4 on 2025-08-28 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_remove_contact_core_contact_email_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="Issue",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^.{5,50}$",
                    ),
                ],
            ),
        ),
    ]
