# Generated by Django 5.2.4 on 2025-08-28 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 9, 4, 20, 19, 13, 600733, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
