# Generated by Django 5.2.4 on 2025-08-30 06:47

import django.core.validators
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_alter_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(default=core.models.default_due_date),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("Urgent", "Urgent"), ("Medium", "Medium"), ("Low", "Low")],
                default="Low",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_priority_choice_invalid",
                        message="Invalid choice.",
                        regex="^(Urgent|Medium|Low)$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__regex", "^(Urgent|Medium|Low)$")),
                name="core_task_priority_check",
            ),
        ),
    ]
