# Generated by Django 5.2.4 on 2025-08-30 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_alter_task_due_date_alter_task_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="title",
            field=models.CharField(
                default="Untitled",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_length_invalid",
                        message="Must be between 5 and 50 characters long.",
                        regex="^.{5,50}$",
                    ),
                ],
            ),
        ),
    ]
