# Generated by Django 5.2.4 on 2025-08-30 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_alter_subtask_title"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="board",
            name="core_board_title_check",
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="core_category_name_check",
        ),
        migrations.RemoveConstraint(
            model_name="contact",
            name="core_contact_name_check",
        ),
        migrations.RemoveConstraint(
            model_name="listoftasks",
            name="core_listoftasks_name_check",
        ),
        migrations.RemoveConstraint(
            model_name="subtask",
            name="core_subtask_title_check",
        ),
        migrations.RemoveConstraint(
            model_name="task",
            name="core_task_title_check",
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(
                default="Untitled",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_length_invalid",
                        message="Must be between 3 and 50 characters long.",
                        regex="^.{3,50}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="Issue",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_length_invalid",
                        message="Must be between 3 and 50 characters long.",
                        regex="^.{3,50}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(
                blank=True,
                default="Anonymous",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_length_invalid",
                        message="Must be between 3 and 50 characters long.",
                        regex="^.{3,50}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="listoftasks",
            name="name",
            field=models.CharField(
                default="Unnamed",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_length_invalid",
                        message="Must be between 3 and 50 characters long.",
                        regex="^.{3,50}$",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="title",
            field=models.CharField(
                default="Untitled",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_length_invalid",
                        message="Must be between 3 and 50 characters long.",
                        regex="^.{3,50}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                default="No description provided.",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_description_length_invalid",
                        message="Must be between 10 and 500 characters long.",
                        regex="^.{10,500}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                default="Untitled",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_title_length_invalid",
                        message="Must be between 3 and 50 characters long.",
                        regex="^.{3,50}$",
                    ),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("title__regex", "^.{3,50}$"),
                    models.Q(
                        ("title__regex", "^\\s+|\\s+$|\\s+(?=\\s)"), _negated=True
                    ),
                ),
                name="core_board_title_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("name__regex", "^.{3,50}$"),
                    models.Q(("name__regex", "^\\s+|\\s+$|\\s+(?=\\s)"), _negated=True),
                ),
                name="core_category_name_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("name", ""),
                    models.Q(
                        ("name__regex", "^.{3,50}$"),
                        models.Q(
                            ("name__regex", "^\\s+|\\s+$|\\s+(?=\\s)"), _negated=True
                        ),
                    ),
                    _connector="OR",
                ),
                name="core_contact_name_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="listoftasks",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("name__regex", "^.{3,50}$"),
                    models.Q(("name__regex", "^\\s+|\\s+$|\\s+(?=\\s)"), _negated=True),
                ),
                name="core_listoftasks_name_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="subtask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("title__regex", "^.{3,50}$"),
                    models.Q(
                        ("title__regex", "^\\s+|\\s+$|\\s+(?=\\s)"), _negated=True
                    ),
                ),
                name="core_subtask_title_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("title__regex", "^.{3,50}$"),
                    models.Q(
                        ("title__regex", "^\\s+|\\s+$|\\s+(?=\\s)"), _negated=True
                    ),
                ),
                name="core_task_title_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(("description__regex", "^.{10,500}$")),
                name="core_task_description_check",
            ),
        ),
    ]
