# Generated by Django 5.2.4 on 2025-08-30 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0076_remove_board_core_board_title_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_email_invalid",
                        message="Invalid email address.",
                        regex="^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_email_length_invalid",
                        message="Must be between 3 and 50 characters long.",
                        regex="^.{3,50}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_length_invalid",
                        message="Must be between 3 and 50 characters long.",
                        regex="^.{3,50}$",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("name__regex", "^.{3,50}$"),
                    models.Q(("name__regex", "^\\s+|\\s+$|\\s+(?=\\s)"), _negated=True),
                ),
                name="core_user_name_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email__regex", "^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$"),
                    ("email__regex", "^.{3,50}$"),
                ),
                name="core_user_email_check",
            ),
        ),
    ]
