# Generated by Django 5.2.4 on 2025-08-30 10:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_alter_user_email_alter_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.user_image_file_path
            ),
        ),
    ]
