# Generated by Django 5.2.4 on 2025-09-02 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_length_invalid",
                        message="Must be between 3 and 50 characters long.",
                        regex="^.{3,50}$",
                    ),
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_name_spacing_invalid",
                        inverse_match=True,
                        message="Leading, trailing, or consecutive spaces are not allowed.",
                        regex="^\\s+|\\s+$|\\s+(?=\\s)",
                    ),
                ],
            ),
        ),
    ]
