# Generated by Django 5.2.4 on 2025-09-02 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listoftasks",
            name="board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lists_of_tasks",
                to="core.board",
            ),
        ),
    ]
