# Generated by Django 5.2.4 on 2025-09-06 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_alter_listoftasks_board"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="task",
            name="core_task_description_check",
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="%(app_label)s_%(class)s_description_length_invalid",
                        message="Must be between 10 and 500 characters long.",
                        regex="^.{10,500}$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("description", ""),
                    ("description__regex", "^.{10,500}$"),
                    _connector="OR",
                ),
                name="core_task_description_check",
            ),
        ),
    ]
