# Generated by Django 5.2.4 on 2025-09-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_remove_task_core_task_description_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="core.contact"
            ),
        ),
    ]
