# Generated by Django 5.2.4 on 2025-09-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_alter_task_assignees"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listoftasks",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="listoftasks",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listoftasks",
            name="position",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
