# Generated by Django 5.2.4 on 2025-09-28 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_alter_listoftasks_options_listoftasks_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listoftasks",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("order",)},
        ),
        migrations.RemoveConstraint(
            model_name="listoftasks",
            name="unique_position_per_board",
        ),
        migrations.RemoveConstraint(
            model_name="task",
            name="unique_position_per_list",
        ),
        migrations.RemoveField(
            model_name="listoftasks",
            name="position",
        ),
        migrations.RemoveField(
            model_name="task",
            name="position",
        ),
        migrations.AlterField(
            model_name="listoftasks",
            name="board",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lists_of_tasks",
                to="core.board",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="core.listoftasks",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, verbose_name="order"
            ),
        ),
        migrations.AddConstraint(
            model_name="listoftasks",
            constraint=models.UniqueConstraint(
                fields=("board", "order"), name="unique_order_per_board"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("list", "order"), name="unique_order_per_list"
            ),
        ),
    ]
