# Generated by Django 5.2.4 on 2025-09-28 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_alter_listoftasks_options_alter_task_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="list",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="core.listoftasks",
            ),
            preserve_default=False,
        ),
    ]
