# Generated by Django 5.2.4 on 2025-09-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_alter_task_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listoftasks",
            options={"ordering": ("order",), "verbose_name_plural": "ListsOfTasks"},
        ),
    ]
