# Generated by Django 5.2.4 on 2025-09-30 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_alter_task_user"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="task",
            name="unique_order_per_list",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="list",
            new_name="list_of_tasks",
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.category",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("list_of_tasks", "order"), name="unique_order_per_list"
            ),
        ),
    ]
