# Generated by Django 5.2.4 on 2025-10-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_remove_task_unique_order_per_list_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subtask",
            name="user",
        ),
    ]
