# Generated by Django 5.2.4 on 2025-10-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0093_remove_subtask_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
    ]
