# Generated by Django 5.2.4 on 2025-11-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0094_remove_task_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listoftasks",
            name="user",
        ),
    ]
