# Generated by Django 5.2.8 on 2025-11-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_remove_listoftasks_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email__gt", ""),
                    ("name__gt", ""),
                    ("phone_number__gt", ""),
                    _connector="OR",
                ),
                name="core_contact_at_least_one_contact_info",
            ),
        ),
    ]
