# Generated by Django 5.2.8 on 2025-11-22 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_contact_core_contact_at_least_one_contact_info"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="listoftasks",
            name="unique_order_per_board",
        ),
    ]
