# Generated by Django 3.2.23 on 2024-01-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20231117_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
