"""
This type stub file was generated by pyright and manually refined.
"""

from __future__ import annotations

from typing import Any
from datetime import datetime

from django.db import models

from core.models import User

AUTH_USER_MODEL: str
TOKEN_GENERATOR_CLASS: Any

__all__ = [
    "ResetPasswordToken",
    "get_password_reset_token_expiry_time",
    "get_password_reset_lookup_field",
    "clear_expired",
]

class ResetPasswordToken(models.Model):
    class Meta:
        verbose_name: str
        verbose_name_plural: str

    @staticmethod
    def generate_key() -> str:
        """generates a pseudo random code using os.urandom and binascii.hexlify"""
        ...
    # konkrete Typen für die Felder
    id: int
    user: User
    created_at: datetime
    key: str
    ip_address: str | None
    user_agent: str

    def save(self, *args: Any, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...

def get_password_reset_token_expiry_time() -> int:
    """
    Returns the password reset token expiry time in hours (default: 24)
    """
    ...

def get_password_reset_lookup_field() -> str:
    """
    Returns the password reset lookup field (default: email)
    """
    ...

def clear_expired(expiry_time: datetime) -> None:
    """
    Remove all expired tokens
    :param expiry_time: Token expiration time
    """
    ...

def eligible_for_reset(self: User) -> bool: ...

UserModel: type[User]
