"""
This type stub file was generated by pyright.
"""

from django.db import models
from django.contrib.auth import get_user_model

AUTH_USER_MODEL = ...
TOKEN_GENERATOR_CLASS = ...
__all__ = ['ResetPasswordToken', 'get_password_reset_token_expiry_time', 'get_password_reset_lookup_field', 'clear_expired']
class ResetPasswordToken(models.Model):
    class Meta:
        verbose_name = ...
        verbose_name_plural = ...
    
    
    @staticmethod
    def generate_key(): # -> str | Any:
        """ generates a pseudo random code using os.urandom and binascii.hexlify """
        ...
    
    id = ...
    user = ...
    created_at = ...
    key = ...
    ip_address = ...
    user_agent = ...
    def save(self, *args, **kwargs): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


def get_password_reset_token_expiry_time(): # -> Any | int:
    """
    Returns the password reset token expirty time in hours (default: 24)
    Set Django SETTINGS.DJANGO_REST_MULTITOKENAUTH_RESET_TOKEN_EXPIRY_TIME to overwrite this time
    :return: expiry time
    """
    ...

def get_password_reset_lookup_field(): # -> Any | str:
    """
    Returns the password reset lookup field (default: email)
    Set Django SETTINGS.DJANGO_REST_LOOKUP_FIELD to overwrite this time
    :return: lookup field
    """
    ...

def clear_expired(expiry_time): # -> None:
    """
    Remove all expired tokens
    :param expiry_time: Token expiration time
    """
    ...

def eligible_for_reset(self): # -> bool:
    ...

UserModel = get_user_model()
