"""
This type stub file was generated by pyright.
"""

from rest_framework import serializers

__all__ = ['EmailSerializer', 'PasswordTokenSerializer', 'ResetTokenSerializer']
class EmailSerializer(serializers.Serializer):
    email = ...


class PasswordValidateMixin:
    def validate(self, data):
        ...
    


class PasswordTokenSerializer(PasswordValidateMixin, serializers.Serializer):
    password = ...
    token = ...


class ResetTokenSerializer(PasswordValidateMixin, serializers.Serializer):
    token = ...


