"""
This type stub file was generated by pyright.
"""

__all__ = ["reset_password_token_created", "pre_password_reset", "post_password_reset"]
from django.dispatch import Signal

reset_password_token_created = Signal()
pre_password_reset = Signal()
post_password_reset = Signal()
