"""
This type stub file was generated by pyright.
"""

def get_token_generator(): # -> RandomStringTokenGenerator | Any:
    """
    Returns the token generator class based on the configuration in DJANGO_REST_PASSWORDRESET_TOKEN_CONFIG.CLASS and
    DJANGO_REST_PASSWORDRESET_TOKEN_CONFIG.OPTIONS
    :return:
    """
    ...

class BaseTokenGenerator:
    """
    Base Class for the Token Generators

    - Can take arbitrary args/kwargs and work with those
    - Needs to implement the "generate_token" Method
    """
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def generate_token(self, *args, **kwargs):
        ...
    


class RandomStringTokenGenerator(BaseTokenGenerator):
    """
    Generates a random string with min and max length using os.urandom and binascii.hexlify
    """
    def __init__(self, min_length=..., max_length=..., *args, **kwargs) -> None:
        ...
    
    def generate_token(self, *args, **kwargs): # -> str:
        """ generates a pseudo random code using os.urandom and binascii.hexlify """
        ...
    


class RandomNumberTokenGenerator(BaseTokenGenerator):
    """
    Generates a random number using random.SystemRandom() (which uses urandom in the background)
    """
    def __init__(self, min_number=..., max_number=..., *args, **kwargs) -> None:
        ...
    
    def generate_token(self, *args, **kwargs): # -> str:
        ...
    


