"""
This type stub file was generated by pyright.
"""

from django.contrib.auth import get_user_model
from rest_framework.generics import GenericAPIView
from rest_framework.viewsets import GenericViewSet
from django_rest_passwordreset.serializers import EmailSerializer, PasswordTokenSerializer, ResetTokenSerializer

User = get_user_model()
__all__ = ['ResetPasswordValidateToken', 'ResetPasswordConfirm', 'ResetPasswordRequestToken', 'reset_password_validate_token', 'reset_password_confirm', 'reset_password_request_token', 'ResetPasswordValidateTokenViewSet', 'ResetPasswordConfirmViewSet', 'ResetPasswordRequestTokenViewSet']
HTTP_USER_AGENT_HEADER = ...
HTTP_IP_ADDRESS_HEADER = ...
def clear_expired_tokens(): # -> None:
    """
    Delete all existing expired tokens
    """
    ...

def generate_token_for_email(email, user_agent=..., ip_address=...): # -> ResetPasswordToken | None:
    ...

class ResetPasswordValidateToken(GenericAPIView):
    """
    An Api View which provides a method to verify that a token is valid
    """
    throttle_classes = ...
    permission_classes = ...
    serializer_class = ResetTokenSerializer
    authentication_classes = ...
    def post(self, request, *args, **kwargs): # -> Response:
        ...
    


class ResetPasswordConfirm(GenericAPIView):
    """
    An Api View which provides a method to reset a password based on a unique token
    """
    throttle_classes = ...
    permission_classes = ...
    serializer_class = PasswordTokenSerializer
    authentication_classes = ...
    def post(self, request, *args, **kwargs): # -> Response:
        ...
    


class ResetPasswordRequestToken(GenericAPIView):
    """
    An Api View which provides a method to request a password reset token based on an e-mail address

    Sends a signal reset_password_token_created when a reset token was created
    """
    throttle_classes = ...
    permission_classes = ...
    serializer_class = EmailSerializer
    authentication_classes = ...
    def post(self, request, *args, **kwargs): # -> Response:
        ...
    


class ResetPasswordValidateTokenViewSet(ResetPasswordValidateToken, GenericViewSet):
    """
    An Api ViewSet which provides a method to verify that a token is valid
    """
    def create(self, request, *args, **kwargs): # -> Response:
        ...
    


class ResetPasswordConfirmViewSet(ResetPasswordConfirm, GenericViewSet):
    """
    An Api ViewSet which provides a method to reset a password based on a unique token
    """
    def create(self, request, *args, **kwargs): # -> Response:
        ...
    


class ResetPasswordRequestTokenViewSet(ResetPasswordRequestToken, GenericViewSet):
    """
    An Api ViewSet which provides a method to request a password reset token based on an e-mail address

    Sends a signal reset_password_token_created when a reset token was created
    """
    def create(self, request, *args, **kwargs): # -> Response:
        ...
    


reset_password_validate_token = ...
reset_password_confirm = ...
reset_password_request_token = ...
