"""
This type stub file was generated by pyright.
"""

from abc import ABCMeta, abstractmethod

class Character(metaclass=ABCMeta):
    @staticmethod
    @abstractmethod
    def generate() -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self):  # -> None:
        ...

    def __iter__(self):  # -> Self:
        ...

    def __next__(self):  # -> None:
        ...

class Store(metaclass=ABCMeta):
    @staticmethod
    @abstractmethod
    def generate():  # -> None:
        ...

    def __str__(self) -> str: ...
    def __repr__(self):  # -> None:
        ...

    def __iter__(self):  # -> Self:
        ...

    def __next__(self):  # -> None:
        ...

class Item(metaclass=ABCMeta):
    @staticmethod
    @abstractmethod
    def generate():  # -> None:
        ...

    def __str__(self) -> str: ...
    def __repr__(self):  # -> None:
        ...

    def __iter__(self):  # -> Self:
        ...

    def __next__(self):  # -> None:
        ...
