"""
This type stub file was generated by pyright.
"""

from .Base import Character
from enum import Enum

class Aarakocra(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Aasimer(Character):
    class AasimerType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: AasimerType = ...): # -> str:
        ...
    


class Bugbear(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Centaur(Character):
    class CentaurType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: CentaurType = ...): # -> str:
        ...
    


class Changeling(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Dragonborn(Character):
    class DragonbornType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: DragonbornType = ...): # -> str:
        ...
    


class Drow(Character):
    class DrowType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: DrowType = ...): # -> str:
        ...
    


class Duergar(Character):
    class DuergarType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: DuergarType = ...): # -> str:
        ...
    


class Dwarf(Character):
    class DwarfType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: DwarfType = ...): # -> str:
        ...
    


class Elf(Character):
    class ElfType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: ElfType = ...): # -> str:
        ...
    


class Fetchling(Character):
    class FetchlingType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: FetchlingType = ...): # -> str:
        ...
    


class Firbolg(Character):
    class FirbolgType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: FirbolgType = ...): # -> str:
        ...
    


class Genasi(Character):
    class GenasiType(Enum):
        Air = ...
        Water = ...
        Earth = ...
        Fire = ...
    
    
    @staticmethod
    def generate(gender: GenasiType = ...): # -> str:
        ...
    


class Gith(Character):
    class GithType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: GithType = ...): # -> str:
        ...
    


class Gnome(Character):
    class GnomeType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: GnomeType = ...): # -> str:
        ...
    


class Goblin(Character):
    class GoblinType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: GoblinType = ...): # -> str:
        ...
    


class Goliath(Character):
    class GoliathType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: GoliathType = ...): # -> str:
        ...
    


class Halfling(Character):
    class HalflingType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: HalflingType = ...): # -> str:
        ...
    


class Hobgoblin(Character):
    class HobgoblinType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: HobgoblinType = ...): # -> str:
        ...
    


class Human(Character):
    class HumanType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: HumanType = ...): # -> str:
        ...
    


class HalfElf(Character):
    class HalfElfType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: HalfElfType = ...): # -> str:
        ...
    


class HalfOrc(Character):
    class HalfOrcType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: HalfOrcType = ...): # -> str:
        ...
    


class Kalashtar(Character):
    class KalashtarType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: KalashtarType = ...): # -> str:
        ...
    


class Kenku(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Kobold(Character):
    class KoboldType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: KoboldType = ...): # -> str:
        ...
    


class Lizardfolk(Character):
    class LizardfolkType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: LizardfolkType = ...): # -> str:
        ...
    


class Loxodon(Character):
    class LoxodonType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: LoxodonType = ...): # -> str:
        ...
    


class Minotaur(Character):
    class MinotaurType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: MinotaurType = ...): # -> str:
        ...
    


class Orc(Character):
    class OrcType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: OrcType = ...): # -> str:
        ...
    


class Shifter(Character):
    class ShifterType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: ShifterType = ...): # -> str:
        ...
    


class SimicHybrid(Character):
    class SimicHybridType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: SimicHybridType = ...): # -> str:
        ...
    


class Svirfneblin(Character):
    class SvirfneblinType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: SvirfneblinType = ...): # -> str:
        ...
    


class Tabaxi(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Tiefling(Character):
    class TieflingType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: TieflingType = ...): # -> str:
        ...
    


class Tortle(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Triton(Character):
    class TritonType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: TritonType = ...): # -> str:
        ...
    


class Vedalken(Character):
    class VedalkenType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: VedalkenType = ...): # -> str:
        ...
    


class Warforged(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Yuanti(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


