"""
This type stub file was generated by pyright.
"""

from .Base import Character
from enum import Enum

class Anadi(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Android(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Automaton(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Azarketi(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Catfolk(Character):
    class CatfolkType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: CatfolkType = ...): # -> str:
        ...
    


class Conrasu(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Dhampir(Character):
    class DhampirType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: DhampirType = ...): # -> str:
        ...
    


class Dwarf(Character):
    class DwarfType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: DwarfType = ...): # -> str:
        ...
    


class Elf(Character):
    class ElfType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: ElfType = ...): # -> str:
        ...
    


class Fetchling(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Fleshwarp(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Ghoran(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Gillman(Character):
    class GillmanType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: GillmanType = ...): # -> str:
        ...
    


class Gnoll(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Gnome(Character):
    class GnomeType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: GnomeType = ...): # -> str:
        ...
    


class Goblin(Character):
    class GoblinType(Enum):
        Male = ...
        Female = ...
        Chieftain = ...
    
    
    @staticmethod
    def generate(gender: GoblinType = ...): # -> str:
        ...
    


class Goloma(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Grippli(Character):
    class GrippliType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: GrippliType = ...): # -> str:
        ...
    


class Halfling(Character):
    class HalflingType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: HalflingType = ...): # -> str:
        ...
    


class Hobgoblin(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Human(Character):
    class HumanType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: HumanType = ...): # -> str:
        ...
    


class Ifrit(Character):
    class IfritType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: IfritType = ...): # -> str:
        ...
    


class Kashrishi(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Kitsune(Character):
    class KitsuneType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: KitsuneType = ...): # -> str:
        ...
    


class Kobold(Character):
    class KoboldType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: KoboldType = ...): # -> str:
        ...
    


class Leshy(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Lizardfolk(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Merfolk(Character):
    class MerfolkType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: MerfolkType = ...): # -> str:
        ...
    


class Nagaji(Character):
    class NagajiType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: NagajiType = ...): # -> str:
        ...
    


class Orc(Character):
    class OrcType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: OrcType = ...): # -> str:
        ...
    


class Oread(Character):
    class OreadType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: OreadType = ...): # -> str:
        ...
    


class Poppet(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Ratfolk(Character):
    class RatfolkType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: RatfolkType = ...): # -> str:
        ...
    


class Shisk(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Shoony(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Skeleton(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Sprite(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Strix(Character):
    class StrixType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: StrixType = ...): # -> str:
        ...
    


class Suli(Character):
    class SuliType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: SuliType = ...): # -> str:
        ...
    


class Sylph(Character):
    class SylphType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: SylphType = ...): # -> str:
        ...
    


class Tengu(Character):
    class TenguType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: TenguType = ...): # -> str:
        ...
    


class Tian(Character):
    class TianType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: TianType = ...): # -> str:
        ...
    


class Undine(Character):
    class UndineType(Enum):
        Male = ...
        Female = ...
    
    
    @staticmethod
    def generate(gender: UndineType = ...): # -> str:
        ...
    


class Vanara(Character):
    @staticmethod
    def generate(): # -> str | None:
        ...
    


class Vishkanya(Character):
    @staticmethod
    def generate(): # -> str:
        ...
    


