"""
This type stub file was generated by pyright.
"""

from .Base import Store
from enum import Enum

class Antique(Store):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Clothes(Store):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Enchanter(Store):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Alchemist(Store):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Restaurant(Store):
    class RestaurantType(Enum):
        Diner = ...
        French = ...
        Tavern = ...
    
    
    @staticmethod
    def Tavern(): # -> str:
        ...
    
    @staticmethod
    def Diner(): # -> str:
        ...
    
    @staticmethod
    def French(): # -> str:
        ...
    
    @staticmethod
    def generate(classification=...): # -> str | None:
        ...
    


class Jeweller(Store):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Blacksmith(Store):
    @staticmethod
    def generate(): # -> str:
        ...
    


class General(Store):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Town(Store):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Brothel(Store):
    @staticmethod
    def generate(): # -> str:
        ...
    


class Gunsmith(Store):
    @staticmethod
    def generate(): # -> str | None:
        ...
    


class Guild(Store):
    @staticmethod
    def generate(): # -> str | None:
        ...
    


